#pragma once

#include <string>
#include <vector>

#include "actor.h"

enum eBarButton;
enum PANGYA_ITEM_GROUP;
class CRealMyRoom_EnterSetting;
class FrViewer;
class FrArea;
class FrButton;
class FrEdit;
class FrGiftDlg;
class FrOptionDlg;
class FrKbdManualDlg;
class FrServerDlg;
class FrLoginRsDlg;
class FrRecycleDlg;
class FrTikiMagicBoxDlg;
class FrScratchDlg;
class FrOnelineReqDlg;
class FrNoticeDlg;
class FrLogoutDlg;
class FrSPCardBuffDlg;
class COfflineTradeDlg;
class FrBirthdayEventMissionDlg;
class FrLevelupItemForm;
class FrSubEquipBar;
class WTitleFont;
class Bitmap;
class FrGroupBox;
class FrTabButton;
class CTaskMain : public IActor, public FrCmdTarget
{
	DECLARE_OBJECT(CTaskMain)

	virtual void CloseAllDialogs();
	bool IsActiveRecycleDlg();
	bool IsActiveScratchDlg();
	virtual void OnDestroy();
	virtual void OnPreserveBack(char const*);
	virtual void OnPreLoadInit();
	virtual void OnInit();
	void CheckNaviButtons();
	virtual void OnLoad();
	virtual void OnRestorePreserved();
	void CreateMaketDlg();
	void ChangeRealMyRoom();
	void MakeRealMyRoom();
	virtual void OnProcess(float);

	CTaskMain() { }
	virtual ~CTaskMain() { }

protected:
	virtual bool OnResultSubEquipBar(int, FrForm*);
	virtual void OnUnderBar_ShopUp();
	virtual void OnUnderBar_MyRoomUp();
	virtual void OnUnderBar_CookieUp();
	virtual void OnUnderBar_GuildUp();
	void InitMessenger();
	void InitBongdariShop();
	void InitControls();
	void InitUnderBar();
	void OnUnderBar_TikiMagicBoxInit(int);
	void InitOverBar();
	void EnableUnderBar(bool);
	void ShowAllSubSelection();
	void CloseAllSubSelection();
	bool OnQuitDlgResult(int, FrForm*);
	bool OnOptionDlgResult(int, FrForm*);
	bool OnNotifyOneDlgResult(int, FrForm*);
	bool OnLoginRsDlgResult(int, FrForm*);
	bool OnMaketListDlgResult(int, FrForm*);
	bool OnKbdManualDlgResult(int, FrForm*);
	char const* MakeStatusString2(int, int, int);
	char const* MakeStatusString3(int, int, int);
	void SetBGMNone();
	bool CompletedMission_Result(int, FrForm*);
	unsigned long GetCategoryFlag(int);
	void CalcUIOffset(bool);
	void SetCenterOffset(FrWnd*, float, float);
	void SetLeftOffset(FrWnd*, float);
	void OnUnderBarInit(int);
	void OnUnderTab_Init(int);
	void OnOverBar_Init(int);
	void OnUnderBar_BackInit(int);
	void OnUnderBar_FrontInit(int);
	void OnUnderBar_ItemStorageInit(int);
	void OnUnderBar_GiftInit(int);
	void OnUnderBar_CookieInit(int);
	void OnUnderBar_ExitInit(int);
	void OnUnderBar_TabToolTipInit(int);
	void OnUnderBar_TabBtnInit(int);
	void TurnOnUnderTabBar();
	void TurnOffUnderTabBar();
	void OnUnderBar_MagicBoxInit(int);
	void OnUnderBar_ScratchInit(int);
	void OnUnderBar_BongdariShopInit(int);
	void OnUnderBar_MaketInit(int);
	void OnUnderBar_RankingInit(int);
	void OnUnderBar_GuildInit(int);
	void OnUnderBar_NoticeInit(int);
	void ShowOverAndUnderBar(bool);
	void EnableOverAndUnderBar(bool);
	void OnOverBar_Bar1Init(int);
	void OnOverBar_Bar2Init(int);
	void OnOverBar_Bar3Init(int);
	void OnOverBar_TitleInit(int);
	void OnOverBar_Frame1Init(int);
	void OnOverBar_Frame2Init(int);
	void OnOverBar_Frame3Init(int);
	void OnOverBar_TabInit(int);
	void OnOverBar_TabDown();
	void OnOverBar_CharInit(int);
	void OnOverBar_CaddieInit(int);
	void OnOverBar_ClubInit(int);
	void OnOverBar_AztecInit(int);
	void OnOverBar_MascotInit(int);
	void OnOverBar_CharSelInit(int);
	void OnOverBar_CaddieSelInit(int);
	void OnOverBar_ClubSelInit(int);
	void OnOverBar_AztecSelInit(int);
	void OnOverBar_MascotSelInit(int);
	void OnOverBar_OneLineReqBtnInit(int);
	void OnOverBar_OneLineViewInit(int);
	void OnOverBar_OneLineViewOwnerDraw(int);
	void OnOverBar_OptionInit(int);
	void OnOverBar_MyInfoInit(int);
	void OnOverBar_PangCookieInit(int);
	void OnOverBar_SpecialCardInit(int);
	void OnTreasureAlarmInit(int);
	void OnMessengerBubbleInit(int);
	void OnMessengerBubbleOwnerDraw(int);
	void OnMessengerBubbleEditInit(int);
	void OnMessengerAlarmBtnUp();
	void OnMessengerGiftAlarmBtnInit(int);
	bool OnOnelineReqChkOutDlgResult(int, FrForm*);
	bool OnSpecialCardFormResult(int, FrForm*);
	float Print(float, float, char const*, float, int, float, unsigned long);
	char const* MakeStatusString(int, int, int);
	char const* MakeCardStatusString(int, int);
	void SetRandomBGM();
	void SetTimeVariableBGM();
	void SetConstantBGM(char const*, bool, bool);
	void SendRoomListExitPacket();
	bool GetBtnState(unsigned char, eBarButton);
	void OnUnderBar_ShopInit(int);
	void OnUnderBar_MyRoomInit(int);
	void OnUnderBar_GameInit(int);
	void OnUnderBar_ServerInit(int);
	void SendSubSelectionPacket(PANGYA_ITEM_GROUP);
	void OpenSubEquipBar(WPoint const&, PANGYA_ITEM_GROUP, int);
	void OnOverBar_MascotDown();
	void OnOverBar_PangCookieOwnerDraw(int);
	void OnBarHoverOn(int);
	void OnBarHoverOff(int);
	void OnBarTooltipOwnerDraw(int);
	void OnOverBar_SpecialCardUp();
	void OnOverBar_MessengerInit(int);
	void OnOverBar_MessengerUp();
	void OnTreasureAlarmUp();
	void OnMessengerAlarmBtnInit(int);
	bool OnWaitDlgResult(int, FrForm*);
	bool OnServerDlgResult(int, FrForm*);
	bool OnRecycleDlgResult(int, FrForm*);
	bool OnTikiMagicBoxDlgResult(int, FrForm*);
	bool OnBongdariDlgResult(int, FrForm*);
	bool OnScratchDlgResult(int, FrForm*);
	bool OnOnelineReqDlgResult(int, FrForm*);
	bool OnNoticeDlgResult(int, FrForm*);
	void TurnOn3DBackground();
	void TurnOff3DBackground();
	void SendRoomExitPacket();
	void OpenWaitedLayout();
	void UpdateSiteInfo();
	void OpenInformation(unsigned long);
	bool OnRMR_ResultSetting(int, FrForm*);
	void OnUnderBar_BackUp();
	void OnUnderBar_FrontUp();
	void OnUnderBar_GameUp();
	void OnUnderBar_ServerUp();
	void OnUnderBar_ExitUp();
	void OnUnderBar_TabBtnUp();
	void OnUnderBar_MagicBoxUp();
	void OnUnderBar_TikiMagicBoxUp();
	void OnUnderBar_ScratchUp();
	void OnUnderBar_BongdariShopUp();
	void OnUnderBar_MaketUp();
	void OnUnderBar_RankingUp();
	void OnUnderBar_NoticeUp();
	void ProcessOverBar();
	void OnOverBar_CharDown();
	void OnOverBar_CaddieDown();
	void OnOverBar_ClubDown();
	void OnOverBar_AztecDown();
	void OnOverBar_AztecOwnerDraw(int);
	void OnOverBar_AztecSelOwnerDraw(int);
	void OnOverBar_SiteInit(int);
	void OnOverBar_OneLineReqBtnUp();
	void OnOverBar_OptionUp();
	void OnOverBar_MyInfoUp();
	bool OnNotifyDlgResult(int, FrForm*);
	void OnUnderBar_ItemStorageUp();
	void OnUnderBar_GiftUp();
	void OnOverBar_CharOwnerDraw(int);
	void OnOverBar_CaddieOwnerDraw(int);
	void OnOverBar_ClubOwnerDraw(int);
	void OnOverBar_MascotOwnerDraw(int);
	void OnOverBar_CharSelOwnerDraw(int);
	void OnOverBar_CaddieSelOwnerDraw(int);
	void OnOverBar_ClubSelOwnerDraw(int);
	void OnOverBar_MascotSelOwnerDraw(int);
	void OnMessengerGiftAlarmBtnUp();
	bool OnLevelupFormResult(int, FrForm*);
	void HandleMsgCommon(MsgObject const&);

private:
	void NotifyServerControlMsg(int);
	void _DrawSelection(FrViewer*, WRect&, eBarButton, FrGraphicInterface*);

	DECLARE_FRESH_MSGMAP()

protected:
	CRealMyRoom_EnterSetting* m_pRMREnterSetting;
	FrButton* m_pUnderBarBack;
	FrButton* m_pUnderBarFront;
	FrButton* m_pUnderBarShop;
	FrButton* m_pUnderBarMyRoom;
	FrButton* m_pUnderBarItemStorage;
	FrButton* m_pUnderBarGift;
	FrButton* m_pUnderBarCookie;
	FrButton* m_pUnderBarGame;
	FrButton* m_pUnderBarServer;
	FrButton* m_pUnderBarExit;
	FrButton* m_pOverBarSpecialCard;
	FrButton* m_pOverBarMessenger;
	FrButton* m_pOverBarMyInfo;
	FrButton* m_pOverBarOption;
	FrButton* m_pUnderBarMagicBox;
	FrButton* m_pUnderBarBongdariShop;
	FrButton* m_pUnderBarRanking;
	FrButton* m_pUnderBarGuild;
	FrButton* m_pUnderBarNotice;
	FrButton* m_pUnderBarMaket;
	FrButton* m_pUnderBarScratch;
	FrGroupBox* m_pOverBar;
	FrGroupBox* m_pUnderTab;
	FrGroupBox* m_pUnderBar;
	FrButton* m_pUnderBarTabBtn;
	FrArea* m_pUnderBarTabToolTip;
	FrButton* m_pOverBarOneLineReqBtn;
	FrArea* m_pOverBarOneLineView;
	FrArea* m_pOverBarBar1;
	FrArea* m_pOverBarBar2;
	FrArea* m_pOverBarBar3;
	FrArea* m_pOverBarFrame1;
	FrArea* m_pOverBarFrame2;
	FrArea* m_pOverBarFrame3;
	FrArea* m_pOverBarTitle;
	FrTabButton* m_pOverBarTab;
	FrViewer* m_pOverBarChar;
	FrViewer* m_pOverBarCaddie;
	FrViewer* m_pOverBarAztec;
	FrViewer* m_pOverBarClub;
	FrViewer* m_pOverBarMascot;
	FrViewer* m_pOverBarCharSel;
	FrViewer* m_pOverBarCaddieSel;
	FrViewer* m_pOverBarAztecSel;
	FrViewer* m_pOverBarClubSel;
	FrViewer* m_pOverBarMascotSel;
	FrStatic* m_pOverBarSite;
	FrArea* m_pOverBarPangCookie;
	Bitmap* m_pPangCookieBmp[4];
	bool m_bOverBarFlag0;
	bool m_bOverBarFlag1;
	FrEdit* m_pMessengerBubbleEdit;
	FrArea* m_pMessengerBubble;
	Bitmap* m_pMessengerBubbleBmp[3];
	FrButton* m_pMessengerBtn;
	FrButton* m_pMessengerAlarmBtn;
	FrButton* m_pMessengerGiftAlarmBtn;
	FrButton* m_pTreasureAlarm;
	unsigned long m_reserved118;
	unsigned long m_reserved11c;
	bool m_bBongdariShop0;
	bool m_bBongdariShop1;
	bool m_bBongdariShop2;
	FrGiftDlg* m_pGiftDlg;
	FrOptionDlg* m_pOptionDlg;
	FrKbdManualDlg* m_pKbdManualDlg;
	FrServerDlg* m_pServerDlg;
	FrLoginRsDlg* m_pLoginRsDlg;
	FrRecycleDlg* m_pRecycleDlg;
	FrTikiMagicBoxDlg* m_pTikiMagicBoxDlg;
	FrScratchDlg* m_pScratchDlg;
	FrOnelineReqDlg* m_pOnelineReqDlg;
	FrForm* m_pWaitDlg;
	FrNoticeDlg* m_pNoticeDlg;
	FrForm* m_pDlg150;
	FrForm* m_pNotifyOneDlg;
	FrLogoutDlg* m_pQuitDlg;
	FrSPCardBuffDlg* m_pSpecialCardDlg;
	COfflineTradeDlg* m_pMaketDlg;
	FrBirthdayEventMissionDlg* m_pMissionDlg[5];
	std::vector<FrLevelupItemForm*> m_levelupForms;
	float m_fKbdManualTime;
	int m_hoverBtn;
	bool m_bShowSubSelection;
	unsigned long m_subSelTypeId;
	unsigned long m_subSelItemId;
	bool m_bUnderTabOn;
	WTitleFont* m_pTitleFont;
	float m_offsetX;
	float m_offsetY;
	float m_screenWidth;
	float m_screenHeight;
	unsigned long m_reserved1b4;
	std::string m_waitedLayout;
	bool m_bGiftUp;
	unsigned long m_reserved1d8;
	FrSubEquipBar* m_pSubEquipBar;
};
