#pragma once

enum eBarButton
{
	TOOLTIP_BACK,
	TOOLTIP_FRONT,
	TOOLTIP_SHOP,
	TOOLTIP_MYROOM,
	TOOLTIP_DOL,
	RMR_RM_POSTBOX,
	TOOLTIP_COOKIE,
	TOOLTIP_GAME,
	TOOLTIP_SERVER,
	TOOLTIP_EXIT,
	TOOLTIP_SPECIAL_CARD,
	TOOLTIP_MSN,
	TOOLTIP_MYINFO,
	TOOLTIP_OPTION,
	TOOLTIP_MAGICBOX,
	TOOLTIP_BONG,
	TOOLTIP_RANKING,
	TOOLTIP_GUILD,
	TOOLTIP_NOTICE,
	RMR_TOOLTIP_MARKET,
	TOOLTIP_SCRATCH,
	TOOLTIP_PLAY,
	TOOLTIP_BUY,
	TOOLTIP_GIFT,
	TOOLTIP_BUYALL,
	TOOLTIP_BUYRESET,
	TOOLTIP_EQUIP,
	TOOLTIP_MOVEGIFT,
	TOOLTIP_DELETE,
	TOOLTIP_RESET,
	TOOLTIP_REEMPLOY,
	TOOLTIP_REPLY,
	TOOLTIP_HANDSEL,
	TOOLTIP_OPENGIFT,
	TOOLTIP_REPORT,
	TOOLTIP_UPGRADE,
	TOOLTIP_DOWNGRADE,
	TOOLTIP_EQUIPCANCEL,
	TOOLTIP_EQUIPRESET,
	TOOLTIP_CARD,
	TOOLTIP_CHARACTER,
	TOOLTIP_CADDIE,
	TOOLTIP_CLUB,
	TOOLTIP_AZTEC,
	TOOLTIP_MASCOT,
	UCC_TOOLTIP_DRAW,
	UCC_TOOLTIP_COPY,
	UCC_TOOLTIP_DRAG,
	UCC_TOOLTIP_GRID,
	UCC_TOOLTIP_PAINT,
	UCC_TOOLTIP_REDO,
	UCC_TOOLTIP_UNDO,
	UCC_TOOLTIP_RESET,
	UCC_TOOLTIP_ZOOMIN,
	UCC_TOOLTIP_ZOOMOUT,
	UCC_TOOLTIP_SPOID,
	UCC_TOOLTIP_TAB_DRAW,
	UCC_TOOLTIP_TAB_PATTERN,
	UCC_TOOLTIP_TAB_EMOTICON,
	UCC_TOOLTIP_TAB_TEXT,
	UCC_TOOLTIP_REDRAW,
	UCC_TOOLTIP_TEMPSAVE,
	RMR_RM_DECO,
	RMR_RM_LETTER,
	RMR_DELETE,
	RMR_RM_WITHDRAWAL,
	RMR_TOOLTIP_CANCEL,
	RMR_TOOLTIP_EXTEND,
	RMR_ITEM_UPLOAD,
	RMR_TOOLTIP_RETURN,
	TOOLTIP_USE,
	TOOLTIP_PACKAGE,
	MAX_BARBUTTON
};

class CIconToolTip
{
private:
	CIconToolTip();
	~CIconToolTip();

public:
	static CIconToolTip* GetInstance()
	{
		static CIconToolTip _Instance;
		return &_Instance;
	}

	void SetToolTip(eBarButton tip);
	void ClearToolTip();
	bool IsCurToolTip(eBarButton tip);
	void Render();
	int GetCurTipIndex() { return m_curTipIndex; }

private:
	int m_curTipIndex;
	const Bitmap* m_pCurToolTip;
	const Bitmap* m_pToolTip[MAX_BARBUTTON];
};

inline CIconToolTip* TOOLTIP()
{
	return CIconToolTip::GetInstance();
}
